DM: 
  Nacts: 24
  geom: 'alpao'
  max_stroke_in_m: 5e-6   

PYR:
  oversampling: 4           # oversampling for PSF computation
  lambdaInM: 750e-9        # [m] sensor wavelength
  bandWidthInM: 0e-9        # [m] sensor band amplitude
  subapPixSize: 39.5        # subaperture diameter in pix
  subapPixSep: 24           # pixel distance between subaps

CCD:
  detector_shape: [160,160]    # detector pixel size
  RON: 0.3                      # readout noise in e-
  quantum_efficiency: 0.9       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER:
  loopFrequencyInHz: 1500     
  integratorGain: [0.9]           # loop integrator gain
  delay: 2                      # loop delay in steps
  nModes2Correct: [430]           # number of reconstructor modes
  ttOffloadFrequencyInHz: 0     # TBI
  modulationInLambdaOverD: 3.0

TELESCOPE:
  pupilSizeInM: 1.8         # [m] telescope diameter
  centerObscuration: 0.0    # [m] central obscuration diameter
  pupilSizeInPixels: 128    # pixels across the pupil diameter
  throughput: 0.11          # accounting for beam splitter

ATMO:
  outerScaleInM: 25         # [m]
  r0: 10e-2                          # [m]
  cn2: [55, 20, 10, 10, 5]
  windSpeed: [10, 10, 12, 12, 16]     # [m/s]
  windAngle: [-12, 44, 0, 123, -132]  # [deg] CCW from East

LOOP:
  nIterations: 2000
  starMagnitude: 1.0
  simFreqHz: 1500          # simulation frequency in Hz
  recompute: False         # if False, any calibration data saved from 
                           # previous runs is loaded rather than recomputed
