DM: 
  Nacts: 24
  geom: 'alpao'
  max_stroke_in_m: 5e-6   

PYR:
  oversampling: 4           # oversampling for PSF computation
  lambdaInM: 750e-9        # [m] sensor wavelength
  bandWidthInM: 0e-9        # [m] sensor band amplitude
  subapPixSize: 35.5        # subaperture diameter in pix
  subapPixSep: 24          # pixel distance between subaps

CCD:
  detector_shape: [144,144]       # detector pixel size
  RON: 0.3                      # readout noise in e-
  quantum_efficiency: 0.9       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER:
  loopFrequencyInHz: 2000     
  integratorGain: [1.1,0.9]          # loop integrator gain
  delay: 2                      # loop delay in steps
  nModes2Correct: [2,413]           # number of reconstructor modes
  modulationInLambdaOverD: 3.0

TELESCOPE:
  pupilSizeInM:       1.8    # [m] telescope diameter
  centerObscuration:  0.6    # [m] central obscuration diameter
  pupilSizeInPixels:  160    # pixels across the pupil diameter
  throughput:         0.11          
  spiders:
    angles:   [40,140,-40,-140] # [deg] CCW from East
    widthInM: 0.01              

ATMO:
  outerScaleInM: 25          # [m]
  r0: [12e-2, 10e-2, 10e-2]  # [m]
  windSpeed: [6, 8, 12]      # [m/s]
  windAngle: [-120, 45, 0]   # [deg] CCW from East
  recompute: False

LOOP:
  nIterations: 1000
  starMagnitude: 1.0
  simFreqHz: 2000          # simulation frequency in Hz
  recompute: False         # if False, any calibration data saved from 
                           # previous runs is loaded rather than recomputed
